### ISSUE TITLE
HAproxy config using socket connection instead of localhost?

### ISSUE THREAD

**Issue by jakehilton** [DataDog/the-monitor#28]
Is it possible to configure the datadog agent to gather stats using the stats socket rather than a localhost url?

In this article: https://www.datadoghq.com/blog/how-to-collect-haproxy-metrics/ it does say how to setup socket stats collecting.. but then in the next article it only says how to integrate that using the localhost endpoint.

Thanks for any help.

**Comment by vagelim** [comment]
Hey @jakehilton, good question. Right now our HAProxy integration uses the the python `requests` library to handle connecting to the HAProxy stats page ([see here for code](https://github.com/DataDog/dd-agent/blob/master/checks.d/haproxy.py#L147-L156)).

I'm looking into using the `requests_unixsocket` module as a potential workaround.

**Comment by jakehilton** [comment]
That would be great. Thanks for looking into this.

**Comment by vagelim** [comment]
@jakehilton just to keep you updated:
The original hypothesis didn't work, as the `requests_unixsocket` doesn't allow writing to the socket. 

I am doing some tests in writing to the raw socket. I may have some code to share with you either tonight or by next week, though it will require modifying the `haproxy.py` check in the Datadog Agent and _possibly_ the installation of an additional python package. Will keep you posted!

**Comment by jakehilton** [comment]
Awesome.. thanks for the update.

**Comment by vagelim** [comment]
Finally have a fix for you! The steps to allow the DD Agent to collect HAProxy metrics via the stats socket are below:

Install the `python-haproxy` package to the Agent's environment:  
```
/opt/datadog-agent/embedded/bin/pip install git+https://github.com/nl5887/python-haproxy.git
```
Download the patched Agent check:
```
curl -O https://gist.githubusercontent.com/vagelim/14b3aed7916eefbe398af9cbe5370e4e/raw/53ff3514b0aaa5afc9ae0c2d9645c81d985b838e/haproxy.py
```
Save the patched HAProxy Agent check to checks.d dir:
```
cp haproxy.py /opt/datadog-agent/agent/checks.d/
```

Change the "url" in the HAProxy Agent check YAML (/etc/dd-agent/conf.d/haproxy.yaml) to your stats socket:
```
- url: /run/haproxy/admin.sock
```
Add the `dd-agent` user to the `haproxy` user group, so that it can read from/write to the socket:

```
usermod -a -G haproxy dd-agent
```

Restart all the things:
```
service datadog-agent restart
service haproxy restart
```
(you may have to stop and then start haproxy, instead of using `restart`)

Wait ~15 seconds for the Agent to start collecting metrics.

Verify successful collection with:
```dd-agent info```  

You should see output resembling this:

```
  Checks
  ======

    haproxy
    -------
      - instance #0 [OK]
      - Collected 39 metrics, 0 events & 4 service checks
```


Let me know if you hit any issues. If all goes well, I'll see about getting this integration into the Agent.

**Comment by jakehilton** [comment]
Awesome.. I'll give this a whirl and see what happens. Thanks for the help!
