### ISSUE TITLE
Wildcard in a timeseries graph

### ISSUE THREAD

**Issue by jakehilton** [DataDog/the-monitor#29]
Just trying to create a timeseries graph based on a wildcard of the name of the instance.

```
{
  "requests": [
    {
      "q": "avg:system.load.1{name:content*}",
      "type": "line",
      "conditional_formats": [],
      "aggregator": "avg"
    }
  ],
  "viz": "timeseries"
}
```

You get the idea.. trying to match on any server with name content but it breaks horribly. No carnage but it just turns red. Am I missing something? My google foo is failing me.

**Comment by jakehilton** [comment]
Oops.. wrong projects. Will move to applicable one.

**Comment by vagelim** [comment]
@jakehilton you can use wildcards in metrics by setting [template variables](http://docs.datadoghq.com/guides/templating/) in your expressions. (I know you closed the issue but I think that might be what you're looking for.)

**Comment by jakehilton** [comment]
Awesome.. I'll check those out. Thank you for the quick reply.

**Comment by jakehilton** [comment]
Hmm.. seems I can't have a template variable based on a wild card. So still not working.

**Comment by vagelim** [comment]
An alternative solution might be to [add a tag to those hosts](http://docs.datadoghq.com/guides/tagging/) that you would otherwise filter by wildcard. For example, assigning all of your content* hosts with a "content" tag, and then filter on that tag. 

I'm sorry I couldn't be of more help. If the above proposed solution doesn't work, there's always our awesome [support team](https://www.datadoghq.com/support/).

**Comment by jakehilton** [comment]
The tagging did it for me.. although a wildcard match would have been handy. Thanks!
