### ISSUE TITLE
NGINX 5xx errors monitoring

### ISSUE THREAD

**Issue by tuliomonteazul** [DataDog/the-monitor#80]
Is there a way to monitor NGINX 5xx errors with NGINX (open-source)?
I saw an [old article](https://www.datadoghq.com/blog/how-to-collect-nginx-metrics/) that says it's only available for NGINX Plus.
But on the [most recent article](https://www.datadoghq.com/blog/how-to-monitor-nginx-with-datadog/) there's nothing saying about that.

**Comment by johnaxel** [comment]
The stub_status_module for OSS NGINX doesn't include metrics about 5xx errors, but you _can_ get that info by parsing your logs. So there is a way to monitor 5xx errors with the free, open source NGINX, but you need a system to read and parse your logs (rather than just scraping the stats from the stub_status page at regular intervals). Does that answer your question @tuliomonteazul ?

**Comment by tuliomonteazul** [comment]
@johnaxel Yes, thank you! My solution was to send to my log system (LogEntries) and setup a monitor there
